### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by garyvh2** [doriandres/lit-context#4]

**Comment by garyvh2** [comment]
@all-contributors please add @doriandres for code ideas doc maintenance

**Comment by garyvh2** [comment]
@all-contributors please add @doriandres for code ideas doc maintenance
@all-contributors please add @garyvh2 for code ideas infra

**Comment by garyvh2** [comment]
@all-contributors please add @doriandres for code ideas doc maintenance

**Comment by doriandres** [comment]
@all-contributors please add @doriandres for code ideas doc maintenance

**Comment by doriandres** [comment]
@all-contributors please add @doriandres for code ideas doc maintenance
